name: Deploy to Live Server

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy to FTP Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      
      - name: Sync Files to Server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./
          server-dir: ./
          exclude: |
            **/.git*
            **/.git*/**
            .github/**
            node_modules/**
            vendor/**
